export enum EtatCourrier {
  EN_ATTENTE = 'EN_ATTENTE',
  EN_COURS = 'EN_COURS',
  REJETE = 'REJETE',
  ACCEPTE = 'ACCEPTE',
  ARCHIVE = 'ARCHIVE',
  DISTRIBUE = 'DISTRIBUE',
  TRAITE = 'TRAITE',
  COMPLIMENT_INFORMATION = 'COMPLIMENT_INFORMATION',
}
